-----------LAB-13-------------------------


CREATE TABLE STUDENT_13(RNO INT PRIMARY KEY,NAME VARCHAR(50),BRANCH VARCHAR(50),SPI DECIMAL(4,2),BKLOG INT)

SELECT * FROM STUDENT_13

--1--
CREATE VIEW vwPERSON AS SELECT * FROM STUDENT_13

SELECT * FROM vwPERSON

--2--
CREATE VIEW vwSTUDENT_DETAILS AS SELECT NAME,BRANCH,SPI FROM STUDENT_13
SELECT * FROM vwSTUDENT_DETAILS

--3--
CREATE VIEW vwAcademic as select RNO,NAME,BRANCH FROM STUDENT_13
SELECT * FROM vwAcademic
--4--
CREATE VIEW vwStudent_Data AS SELECT * FROM STUDENT_13 WHERE BKLOG>2
SELECT * FROM vwStudent_Data

--5--
CREATE VIEW vwStudent_Pattern AS SELECT RNO,NAME,BRANCH FROM STUDENT_13 WHERE NAME LIKE '    '
SELECT * FROM vwStudent_Pattern

--6--
INSERT INTO vwAcademic VALUES(107,'MEET','ME')
SELECT * FROM vwAcademic
--7--
UPDATE vwSTUDENT_DETAILS SET BRANCH='ME' WHERE NAME='AMIT'
SELECT * FROM vwSTUDENT_DETAILS

--8--
DELETE FROM vwAcademic WHERE RNO=104
SELECT * FROM vwAcademic

--9--
CREATE VIEW vwALL AS SELECT * FROM STUDENT_13 WHERE SPI>9.5
SELECT * FROM vwALL

--10--
CREATE VIEW vwZEROBKLOG AS SELECT* FROM STUDENT_13 WHERE BKLOG=0

SELECT * FROM vwZEROBKLOG