------LAB-14--------
--SYNTAX--
--CREATE FUNCTION FUNCTIONAME ( PARAMETERS DATATYPE)
--RETURN DATATYPE
-----------

--1--
ALTER FUNCTION PRINT1()
RETURNS VARCHAR(100)
AS
BEGIN 
DECLARE @I INT,@STRING VARCHAR(100) = ''
SET @I=1
WHILE @I<=10
	BEGIN
		 SELECT @STRING = @STRING+CAST(@I AS VARCHAR(100))+','
		SET @I=@I+1
	END
	RETURN @STRING
END

SELECT DBO.PRINT1()

--2--
ALTER FUNCTION ODDEVEN(@J INT)
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @RETURN VARCHAR(100)=''
	IF @J%2<>0
		BEGIN
			SET @RETURN='ODD'
		END
	ELSE 
		BEGIN 
			SET @RETURN='EVEN'
		END
		RETURN @RETURN
END
SELECT DBO.ODDEVEN(5)

--3--
ALTER FUNCTION PRINTODD()
RETURNS VARCHAR(100)
AS
BEGIN 
DECLARE @ODD INT,@DEMO VARCHAR(100) =''
SET @ODD=1
WHILE @ODD<=10
	BEGIN
		IF @ODD%2<>0
		BEGIN
		
			 SELECT @DEMO = @DEMO+CAST(@ODD AS VARCHAR(100))+','
		END
		SET @ODD=@ODD+1
	END
	RETURN @DEMO
END
SELECT DBO.PRINTODD()
--4--

ALTER FUNCTION SUMOF1TO10()
RETURNS INT
AS
BEGIN
DECLARE @S INT =1,@ANS INT =0
WHILE @S<=50
	BEGIN
		 SET @ANS=@ANS+@S
		SET @S=@S+1
	END
	RETURN @ANS
END

SELECT DBO.SUMOF1TO10()

--5--
ALTER FUNCTION SUMOFEVEN1TO20()
RETURNS INT 
AS
BEGIN
DECLARE @S INT =1,@ANS INT =0
WHILE @S<=20
	BEGIN
		IF @S%2=0
			BEGIN
				 SET @ANS=@ANS+@S
			END
			SET @S=@S+1
	END
	RETURN @ANS
END

SELECT DBO.SUMOFEVEN1TO20()

--6--
ALTER FUNCTION PRIMEORNOT(@S INT)
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @PRIME VARCHAR(100) ='',@I INT =2,@FLAG INT =0
	WHILE @I<@S/2
		BEGIN
			IF @S%@I=0
			BEGIN
				SET @FLAG =1
				BREAK
			END
			ELSE 
			BEGIN
				SET @PRIME='PRIME'
			END
			SELECT @S=@S+1
		END 
		RETURN @PRIME
END

SELECT DBO.PRIMEORNOT(17)
