-------------LAB-12--------------
--TABLES COMES FROM LAB-10 -----

SELECT * FROM STUDENT
SELECT * FROM RESULT

--1--
CREATE PROCEDURE SPGETFULLRECORD 
AS
BEGIN
SELECT NAME,BRANCH,SPI,STUDENT.RNO FROM STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
END
EXEC SPGETFULLRECORD

--2--
CREATE PROCEDURE SPGETDETAILFROMROLLNOUSER
@RNO INT 
AS
BEGIN
SELECT STUDENT.RNO,NAME,BRANCH,SPI FROM STUDENT 
FULL OUTER JOIN 
RESULT 
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.RNO =@RNO
END

EXEC SPGETDETAILFROMROLLNOUSER 107

--3--
CREATE PROCEDURE SPINSERTVALUE 
AS
BEGIN
INSERT INTO STUDENT VALUES(107,'RAJ','EE')
END

SELECT * FROM STUDENT
EXEC SPINSERTVALUE

--4--
CREATE PROCEDURE SPUPDATEROW
AS
BEGIN
UPDATE STUDENT SET BRANCH='EC' WHERE RNO = 105
END
EXEC SPUPDATEROW

--5--
CREATE PROCEDURE SPDELETERECORD
AS
BEGIN
DELETE FROM STUDENT WHERE RNO=103
END
EXEC SPDELETERECORD


--INSERT MULTIPLE VALUE EXECUTE LIKE THIS--
CREATE PROCEDURE SPINSERTMULTIPLEDETAIL
@RNO INT,
@NAME VARCHAR(50),
@BRANCH VARCHAR(50)
AS
INSERT INTO STUDENT VALUES(@RNO,@NAME,@BRANCH)

EXEC SPINSERTMULTIPLEDETAIL 108,'KISHAN','CSE'

SELECT * FROM STUDENT	