------------------LAB-10---------------------
CREATE TABLE STUDENT 
(RNO INT ,NAME VARCHAR(50) , BRANCH VARCHAR(50))

INSERT INTO STUDENT VALUES (101,'RAJU','CE')
INSERT INTO STUDENT VALUES (102,'AMIT','CE')
INSERT INTO STUDENT VALUES (103,'SANJAY','ME')
INSERT INTO STUDENT VALUES (104,'NEHA','EC')
INSERT INTO STUDENT VALUES (105,'MEERA','EE')
INSERT INTO STUDENT VALUES (106,'MAHESH','ME')

CREATE TABLE RESULT (RNO INT ,SPI DECIMAL(4,2))
INSERT INTO RESULT VALUES(101,8.8)
INSERT INTO RESULT VALUES(102,9.2)
INSERT INTO RESULT VALUES(103,7.6)
INSERT INTO RESULT VALUES(104,8.2)
INSERT INTO RESULT VALUES(105,7.0)
INSERT INTO RESULT VALUES(107,8.9)

CREATE TABLE EMPLOYEE (EMPLOYEENO VARCHAR(50), NAME VARCHAR(50) ,MANAGERNO VARCHAR(50))

INSERT INTO EMPLOYEE VALUES('E01','TARUN',NULL)
INSERT INTO EMPLOYEE VALUES('E02','ROHAN','E02')
INSERT INTO EMPLOYEE VALUES('E03','PRIYA','E01')
INSERT INTO EMPLOYEE VALUES('E04','MILAN','E03')
INSERT INTO EMPLOYEE VALUES('E05','JAY','E01')
INSERT INTO EMPLOYEE VALUES('E06','ANJANA','E04')

------------------------------------------------------10.1---------------------------------------
SELECT * FROM STUDENT 
INNER JOIN 
RESULT
ON STUDENT.RNO=RESULT.RNO


--1--
SELECT * FROM STUDENT 
CROSS JOIN 
RESULT
--OR--
SELECT * FROM 
STUDENT,RESULT

--2--
SELECT NAME,BRANCH,SPI,STUDENT.RNO FROM STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH='CE'

--3--
SELECT STUDENT.RNO,NAME,BRANCH,SPI FROM STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH <> 'EC'

--4--
SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT
INNER JOIN
RESULT 
ON STUDENT.RNO = RESULT.RNO
GROUP BY BRANCH
--5--
SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT
INNER JOIN
RESULT 
ON STUDENT.RNO = RESULT.RNO
GROUP BY BRANCH 
ORDER BY AVG(SPI)

--6--
SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT
INNER JOIN
RESULT 
ON STUDENT.RNO = RESULT.RNO
WHERE BRANCH IN ('CE','ME')
GROUP BY BRANCH 

--7--
SELECT * FROM STUDENT 
LEFT OUTER JOIN 
RESULT
ON STUDENT.RNO=RESULT.RNO

--8--
SELECT * FROM STUDENT 
RIGHT OUTER JOIN 
RESULT
ON STUDENT.RNO=RESULT.RNO

--9--
SELECT * FROM STUDENT 
FULL OUTER JOIN 
RESULT
ON STUDENT.RNO=RESULT.RNO

--10--

SELECT E.NAME ,M.NAME FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON E.MANAGERNO = M.EMPLOYEENO


--------------------------------------------------10.2---------------------------------------------------
CREATE TABLE CITY (CITYID INT PRIMARY KEY, CITYNAME VARCHAR(50) UNIQUE,PINCODE VARCHAR(6),REMARKS VARCHAR(250))

INSERT INTO CITY VALUES(1,'RAJKOT','360005','GOOD')
INSERT INTO CITY VALUES(2,'SURAT','335009','VERY GOOD')
INSERT INTO CITY VALUES(3,'BARODA','390001','AWESOME')
INSERT INTO CITY VALUES(4,'JAMNAGAR','361003','SMART')
INSERT INTO CITY VALUES(5,'JUNAGADH','362229','HISTORIC')
INSERT INTO CITY VALUES(6,'MORVI','363641','CERAMIC')

CREATE TABLE VILLAGE (VILLAGEID INT PRIMARY KEY,VILLAGENAME VARCHAR(50), CITYID INT FOREIGN KEY REFERENCES CITY(CITYID))

INSERT INTO VILLAGE VALUES(101,'RAIYA',1)
INSERT INTO VILLAGE VALUES(102,'MADHAPAR',1)
INSERT INTO VILLAGE VALUES(103,'DODKA',3)
INSERT INTO VILLAGE VALUES(104,'FALLA',4)
INSERT INTO VILLAGE VALUES(105,'BHESAN',5)
INSERT INTO VILLAGE VALUES(106,'DHORAJI',5) 
SELECT * FROM VILLAGE

--1--
SELECT VILLAGE.VILLAGENAME,CITY.CITYNAME FROM CITY
INNER JOIN VILLAGE
ON VILLAGE.CITYID = CITY.CITYID
WHERE CITYNAME='RAJKOT'

--2--
SELECT CITY.CITYNAME,VILLAGE.VILLAGENAME,CITY.PINCODE FROM CITY
INNER JOIN VILLAGE
ON VILLAGE.CITYID = CITY.CITYID

--3--
SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGENAME) FROM CITY 
INNER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME
HAVING COUNT(VILLAGE.VILLAGENAME) > 1


--4--
SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGENAME) FROM CITY 
LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME
HAVING COUNT(VILLAGE.VILLAGENAME) = 0

--5--
SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGENAME) FROM CITY 
LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME

--6---DONE BY SUB QUERY---
SELECT COUNT(*) FROM (SELECT CITY.CITYNAME,COUNT(CITY.CITYID) FROM CITY 
left outer JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME
HAVING COUNT(CITY.CITYID) > 1)
---