---------lab-7-----------

--1--
SELECT GETDATE() AS TODAY_DATE

--2--
SELECT GETDATE() + 365

--3--
SELECT CONVERT(VARCHAR(20),GETDATE()) 

--4--FOR DD-MM-YYYY NO. IS 106
SELECT CONVERT(VARCHAR(20),GETDATE(),106)

--5---
SELECT CONVERT(VARCHAR(20),GETDATE(),7)

--6--
SELECT DATEDIFF(MONTH,'2008-12-31','2009-03-31')

--7
SELECT DATEDIFF(YEAR,'2012-01-25','2010-09-14')

--8--
SELECT DATEDIFF(HOUR,'2012-01-25 7:00','2012-01-26 10:30')

--9--
select DAY('2016-05-12'),MONTH('2016-05-12'),YEAR('2016-05-12')

--10--
SELECT DATEADD(YEAR,5,GETDATE())

--11--
SELECT DATEADD(MONTH,-2,GETDATE())

--12--DATENAME IS DATATYPE IS VARCHAR AND DATEPART DATATYPE IS DATETIME
SELECT DATENAME(MONTH,GETDATE()),DATEPART(MONTH,GETDATE())

--13--
SELECT EOMONTH(GETDATE())

--14--
SELECT DATEADD(DAY,30,GETDATE())
--OR--
SELECT GETDATE() + 30

--15--
SELECT DATEDIFF(DAY,'2003-09-20',GETDATE())
SELECT DATEDIFF(MONTH,'2003-09-20',GETDATE())
SELECT DATEDIFF(YEAR,'2003-09-20',GETDATE())

----------AGGREGATE FUNCTIONS-------
CREATE TABLE STUDENT_MARKS
(SID INT NOT NULL,SNAME VARCHAR(50) NOT NULL,MARKS INT NOT NULL)

INSERT INTO STUDENT_MARKS VALUES(1,'JOHN',90)
INSERT INTO STUDENT_MARKS VALUES(2,'MARTIN',80)
INSERT INTO STUDENT_MARKS VALUES(3,'CAROL',89)
INSERT INTO STUDENT_MARKS VALUES(4,'JACK',99)
INSERT INTO STUDENT_MARKS VALUES(5,'ROSE',88)
INSERT INTO STUDENT_MARKS VALUES(6,'MARY',90)

SELECT * FROM STUDENT_MARKS

--1--
SELECT COUNT(SID) AS TOTAL_STUDENT FROM STUDENT_MARKS

--2--
SELECT SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_MARKS

--3--
SELECT AVG(MARKS) AS AVG_MARKS FROM STUDENT_MARKS

--4--
SELECT MIN(MARKS) AS MINI_MARKS FROM STUDENT_MARKS

--5--
SELECT MAX(MARKS) AS MAX_MARKS FROM STUDENT_MARKS