-- LAB-3 --

CREATE TABLE STUDENT ( ENROLLMENT_NO VARCHAR(20),NAME VARCHAR(25),CPI DECIMAL(5,2),BIRTHDATE DATETIME )

--3.1--
ALTER TABLE STUDENT ADD CITY VARCHAR(20),BACKLOG INT NOT NULL

SELECT * FROM STUDENT_MASTER
--3.2--
ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(35)

--3.3--
ALTER TABLE STUDENT ALTER COLUMN CPI INT

--3.4--
SP_RENAME 'STUDENT.ENROLLMENT_NO','ENO','COLUMN'

--3.5-- 
ALTER TABLE STUDENT DROP COLUMN CITY

--3.6--
SP_RENAME 'STUDENT','STUDENT_MASTER'

 --3.7--
 ALTER TABLE STUDENT_MASTER DROP COLUMN BACKLOG

 --3.8--
 ALTER TABLE STUDENT_MASTER ALTER COLUMN  NAME VARCHAR(25) NOT NULL

 --3.9--
 SP_RENAME 'STUDENT_MASTER.BIRTHDATE','BDATE','COLUMN' 

 --3.10--
 ALTER TABLE STUDENT_MASTER ALTER COLUMN ENO VARCHAR(12)